name: Flash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib dev cairngorm-openfl $GITHUB_WORKSPACE
      - name: Build Flash .swc library
        run: haxelib run openfl build flash -debug
