name: Samples

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib install feathersui-rpc-services --quiet
          haxelib dev feathersui-cairngorm ${{ github.workspace }}
      - name: Build samples/cafe-townsend
        working-directory: samples/cafe-townsend
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build flash
          haxelib run openfl build hl
      - name: Build samples/todomvc
        working-directory: samples/todomvc
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build flash
          haxelib run openfl build hl
  build-air:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "33.1"
          accept-license: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib install feathersui-rpc-services --quiet
          haxelib dev feathersui-cairngorm ${{ github.workspace }} 
          haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
      - name: Build samples/cafe-townsend
        working-directory: samples/cafe-townsend
        run: |
          haxelib run openfl build air
      - name: Build samples/todomvc
        working-directory: samples/todomvc
        run: |
          haxelib run openfl build air
