name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-neko:
    strategy:
      matrix:
        haxe-version: [4.2.1]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install utest --quiet
          haxelib dev cairngorm-openfl $GITHUB_WORKSPACE
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test neko

  test-air:
    strategy:
      matrix:
        haxe-version: [4.2.1]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: joshtynjala/setup-adobe-air-action@v1
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install utest --quiet
          haxelib dev cairngorm-openfl ${{ github.workspace }} 
          haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test air
